### ISSUE TITLE
[bounty] Minimal Visual Studio (classic) example of inline completion

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-lsp#2]
We are interested of course in a full working plugin for VS classic, but before going there, we need a minimal example.

We talked to C# experts who tried to decompile MS IntelliSense and Codeium, without much luck. They both too big, not clear what is going on, too many DLLs.

We need a minimal example of inline completion that we can start with. It would be great if it worked with the current LSP server, especially LSP 3.18 InlineCompletion as in #1 , but multiline "hello\nworld" will do, too.

The code must be short, clear. Create a project that compiles into VS classic plugin, demonstrates multiline gray text.

**Comment by olegklimov** [comment]
Some tricky parts as in #1 :

* Showing gray text and completion popup might conflict, the popup has its strengths too. So the decision about which suggestion to show might be tricky, sure it's shouldn't show both at the same time.

* Grey text should not increase visible line counters, for example a code suggestion at line 100 that has 5 lines shouldn't make the next line 106 before it's accepted.

**Comment by haruncurak** [comment]
Hi @olegklimov, happy to give this one a shot! I'll keep you posted as I make progress -

/attempt #2 z

**Comment by haruncurak** [comment]
First Q, just to make sure I understand: By VS classic you mean the .NET-focused standalone IDE Visual Studio, or is. it something else?

**Comment by olegklimov** [comment]
You can read about it there:

https://en.wikipedia.org/wiki/Visual_Studio
https://en.wikipedia.org/wiki/Visual_Studio_Code

**Comment by digital-phoenix** [comment]
/attempt #2

I'll give this issue a shot

**Comment by olegklimov** [comment]
@digital-phoenix nice!

**Comment by olegklimov** [comment]
No it's still open. I didn't see an ongoing effort either.

**Comment by digital-phoenix** [comment]
I should be finished this fairly soon. The biggest issue is that there is very limited documentation around the features needed to implement multiline text without adding it to the file. But I believe I've found everything I need at this point.

**Comment by digital-phoenix** [comment]
<img width="1707" alt="initalTestResults" src="https://github.com/smallcloudai/refact-lsp/assets/350208/77b364cc-55cf-47e4-96a3-6477d4f580b7">

**Comment by digital-phoenix** [comment]
This is starting to come together

**Comment by olegklimov** [comment]
Oh wow! How many DLLs did you have to link? )

**Comment by digital-phoenix** [comment]
The extension only required some standard DLLs. Which include: several System.* DLLs; the Visual studio SDK and it's dependencies; and the Microsoft Presentation Framework for UI rendering.

**Comment by digital-phoenix** [comment]
![VisualStudioDemo](https://github.com/smallcloudai/refact-lsp/assets/350208/a74cd003-e121-4cb1-b47b-a045c35675c1)

**Comment by digital-phoenix** [comment]
I think I have implemented all the requirements for this issue. 
I will post the code soon. 
Let me know if you have any questions.

**Comment by olegklimov** [comment]
Here I have a random link:

https://github.com/jasonlyu123/SvelteVisualStudio

Ultimately we want this completion to work with our LSP server (not a part of this issue). There should be some good way to run it.

**Comment by digital-phoenix** [comment]
I created a new repo with the source code here:
https://github.com/digital-phoenix/MultilineGreyText/tree/main/MultilineGreyText

**Comment by digital-phoenix** [comment]
@olegklimov I believe the code I posted should resolve this issue. Let me know if you have any further questions. 

I sent you a message on the issue for Sublime Lsp with my email so you can add me to the slack. Once you add me to the slack we can talk about the steps required to implement a full Lsp plugin in Visual Studio.

**Comment by olegklimov** [comment]
Fantastic! I'll take a look on Monday.

**Comment by olegklimov** [comment]
OK it's Wednesday, but I finally got to it.

<img width="267" alt="image" src="https://github.com/smallcloudai/refact-lsp/assets/18546213/24271d14-a525-41a4-a138-c05a080f5372">

Here's what I'm getting, trying to open MultilineGreyText solution. I'm using Visual Studio for Mac.

**Comment by olegklimov** [comment]
I found this guide from 2017 

https://learn.microsoft.com/en-us/previous-versions/visualstudio/mac/extending-visual-studio-mac-walkthrough?view=vsmac-2017

But I couldn't follow it on my computer.

I found the guid VS was complaining about on the screenshot above:

https://gist.github.com/vnl/4b1851bfbc923cd3ac0e98aa8d8b2eef

I deleted the line with this guis from `MultilineGreyText.csproj`, and I got this far:

<img width="375" alt="image" src="https://github.com/smallcloudai/refact-lsp/assets/18546213/84780b4a-6e54-411a-9681-6bd8dadca2d6">

If I right-click on "Packages" I can make this happen:

```
  GET https://api.nuget.org/v3/registration5-gz-semver2/microsoft.visualstudio.sdk/index.json
  OK https://api.nuget.org/v3/registration5-gz-semver2/microsoft.visualstudio.sdk/index.json 212ms
Getting restore information for project ~/Projects/MultilineGreyText/MultilineGreyText/MultilineGreyText.csproj
~/Projects/MultilineGreyText/MultilineGreyText/MultilineGreyText.csproj(76,3) : error MSB4019: The imported project "/usr/local/share/dotnet/sdk/7.0.308/Microsoft/VisualStudio/v17.0/VSSDK/Microsoft.VsSDK.targets" was not found. Confirm that the expression in the Import declaration "/usr/local/share/dotnet/sdk/7.0.308/Microsoft/VisualStudio/v17.0/VSSDK/Microsoft.VsSDK.targets" is correct, and that the file exists on disk.
Unable to create package spec for project. '~/Projects/MultilineGreyText/MultilineGreyText/MultilineGreyText.csproj'

```

I feeling it's harder than it should be. Maybe I'm doing something wrong.

**Comment by digital-phoenix** [comment]
@olegklimov It sounds like Microsoft is ending support for Visual Studio classic on mac https://devblogs.microsoft.com/visualstudio/visual-studio-for-mac-retirement-announcement/ . As extension support for Visual Studio mac appears to be very limited. Would it be possible to test this extension on Windows or a virtual machine running Windows?

**Comment by digital-phoenix** [comment]
@olegklimov yeah visual studio for mac extensions appear to be supported primarily through Monodevelop libraries. I'd basically need to create an entirely separate extension to get the extension to work on Mac.

**Comment by jovialcore** [comment]
Hi, anyone still working on this ?

**Comment by digital-phoenix** [comment]
@jovialcore I'm still working on this and it is in the final test phase.

**Comment by olegklimov** [comment]
I tested @digital-phoenix 's code, it's actually pretty good! (as a hello world example)

**Comment by digital-phoenix** [comment]
@olegklimov is there anything left to do for this issue or is it resolved?

**Comment by olegklimov** [comment]
Hey @digital-phoenix I think you need to type "/claim" for workflow to go through
