### ISSUE TITLE
Cargo.lock file is missing

### ISSUE THREAD

**Issue by ser** [smallcloudai/refact-lsp#252]
Per the instructions in the [Cargo Book](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html) best practices guide, Rust applications should always commit the Cargo.lock file in git to ensure a reproducible build.

This file is missing.

**Comment by olegklimov** [comment]
You are right, we need to add that.

**Comment by olegklimov** [comment]
Done!
