### ISSUE TITLE
[rust] Support for LSP 3.18 inline completions

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-lsp#3]
We have an LSP function that does code completion, but it's a custom function. 

Here's the specification from Microsoft:

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#textDocument_inlineCompletion

So we want to keep the custom function, to keep existing plugins working, but also add all the necessary bits and pieces for 3.18 inline completion support.

**Comment by olegklimov** [comment]
Added [LSP custom function example](https://github.com/smallcloudai/refact-lsp/blob/main/examples/lsp_completion.py)

**Comment by olegklimov** [comment]
Hey @AayushMohan @VitthalGupta , based on previous bounties we'd like to avoid several people duplicating the work. Did one of you made any initial progress? Can you shoot a very short video? If the progress is there, I think it better to "assign" this issue to a single person.

**Comment by olegklimov** [comment]
Anyone has progress on this?

**Comment by mahimairaja** [comment]
Kindly close this issue

**Comment by olegklimov** [comment]
This got stuck because we found that LSP calls are not enough anyway, for example we need to know when user accepts the suggestion. And some IDEs send nothing at all for certain programming languages (!), that's unreliable from our POV.

**Comment by PlanetKumbhaj** [comment]
can i fix the issue /attempt #3

**Comment by MayorChristopher** [comment]
Can I work on it

**Comment by Sambit003** [comment]
@olegklimov Can I work on this ?

**Comment by digital-phoenix** [comment]
@olegklimov if this is no longer a valid issue can you close it?

**Comment by Sambit003** [comment]
> @olegklimov if this is no longer a valid issue can you close it? 

This will be the right choice, otherwise it's really misleading

**Comment by olegklimov** [comment]
Right, this thing has self-dissolved...
