### ISSUE TITLE
[new feature] GitLab integration

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-lsp#341]
[Gitlab](https://gitlab.com/) is a service analogous to Github. We don't have to always support Microsoft that owns github, do we?

Let's make a Gitlab integration and make Refact work with issues, merge requests, maybe CI, etc. For functionality you can look at what [Github integration](https://github.com/smallcloudai/refact-lsp/blob/main/src/integrations/integr_github.rs) provides: creating issues, commenting, searching.

It's not clear at this point if they have a command line utility or REST API in Gitlab. Both can be integrated quite easily, a change to only 2 files required (1 file for the new integration, and `tools_description.rs`)

[CONTRIBUTING](https://github.com/smallcloudai/refact-lsp/blob/main/CONTRIBUTING.md)

**Comment by eleensmathew** [comment]
Can I work on this?

**Comment by katrinmaikova** [comment]
@eleensmathew, sure, this issue has been assigned to you! ;)

**Comment by eleensmathew** [comment]
Hey can you unassign me from this issue? I am not familiar with rust.

**Comment by Commit2Cosmos** [comment]
Hi, I would like to give it a go, please. I'm planning to integrate with GLab CLI for now. Should I also add tests for it in `tests/test12_tools_authorize_calls.py`?

**Comment by olegklimov** [comment]
`test12_tools_authorize_calls.py` is about asking confirmation from the user for certain commands, you can set up patterns in `integrations.yaml`. It's not specific to an integration, it's a common mechanism for all the commands.

Not sure if tests are even possible for this kind of thing, create a dummy repository on GitLab, give agent the key, and ask to create an issue, and then delete it?

**Comment by Commit2Cosmos** [comment]
I see, thank you for clarifying this, will give it a try!

**Comment by olegklimov** [comment]
Sure, take a look at my screenshot here https://github.com/smallcloudai/refact-lsp/issues/340 and try to reproduce it, should be more clear how it's supposed to work

**Comment by olegklimov** [comment]
> enabling experimental tools?

It's the --experimental flag :D

target/debug/refact-lsp --address-url Refact --api-key XXXX --http-port 8001 --experimental --workspace-folder ~/code/project_with_git --logs-stderr

and "npm run dev" in `refact-chat-js` that will connect to 8001, the easiest way to try it. (ah yeah right, you already have that running on your screenshot)

**Comment by Commit2Cosmos** [comment]
Exactly what I was looking for, thanks! Get this now, any idea what to do? (I've added my gh key to the default integrations yaml)
<img width="1027" alt="Screenshot 2024-10-22 at 17 00 31" src="https://github.com/user-attachments/assets/c9d4cc91-e85b-4dbf-9dcc-50c513edfe62">

**Comment by Commit2Cosmos** [comment]
> target/debug/refact-lsp --address-url Refact --api-key XXXX --http-port 8001 --experimental --workspace-folder ~/code/project_with_git --logs-stderr

Just what I was looking for, thanks! And the refact-chat-js is quite convenient too.

The code is very similar to the github integration, but it seems to work! Please lmk if you spot any issues or would like me to change something
<img width="1262" alt="Screenshot 2024-10-23 at 11 52 14" src="https://github.com/user-attachments/assets/5344d578-0dee-4d80-ad4d-2560dc9e1605">
<img width="255" alt="Screenshot 2024-10-23 at 11 52 40" src="https://github.com/user-attachments/assets/7c73be27-464a-4f5e-bb4c-a17af5deaa77">
