### ISSUE TITLE
Handle problem case when tokenizer.json is empty

### ISSUE THREAD

**Issue by hazratisulton** [smallcloudai/refact-lsp#39]
Somehow sometimes the file tokenizer.json is empty. To reproduce you can replace correct tokenizer.json with empty file.

**Actual result:**
Plugin says nothing about problem
![Image](https://github.com/smallcloudai/refact-lsp/assets/140423660/1dbb41b3-eedd-4407-848a-6b8ee1d3ec62)
LSP log:
```
ERROR refact_lsp::http::utils:31: /code-completion returning "400 Bad Request"
2023-12-12T22:06:20.910329Z ERROR refact_lsp::custom_error:54: client will see {"detail":"failed to load tokenizer: EOF while parsing a value at line 1 column 0"}
```
If you delete empty file manually it can help, but not always. In some cases it's continue to recreate empty tokenizer.json file (no connection to server with file?) and to fix this problem you need to find correct tokenizer.json and replace empty file.

**Expected result:**
Plugin working. If necessary, the plugin will independently solve problems with tokenizer.json (or inform the user about the problem in clear text about the error and how to fix it)

Tested plugins:
VS Code v2.0.108
JB 1.2.8

**Comment by olegklimov** [comment]
Tested with VSCode:



![Image](https://github.com/smallcloudai/refact-lsp/assets/18546213/da7496ae-555c-42b3-8a03-bf8f32990126)

**Comment by valaises** [comment]
I can relate. Installed on windows VSCode v2.0.108 and caught this bug

**Comment by oxyplay** [comment]
Same bug for me. Enterprise account with VSCode v2.0.108 and v2.0.112 (pre release) versions.

**Comment by hazratisulton** [comment]
Checked plugin v2.0.127 with broken, empty and non existing tokenizer.json - new tokenizer is downloading without problems.
