### ISSUE TITLE
chatbot breaks if set temperature to 0

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-lsp#40]
**Scenario:**
Run docker-compose.yml with chatbot
Open chatbot web ui
Set temperature to 0
Try to use chat

**Expected result:**
Chat is working
or
it's impossible to set temperature to 0

**Actual result:**
Chat is not working
![Image](https://github.com/smallcloudai/refact-lsp/assets/140423660/6548fabb-4533-4ed1-96ed-b67914e9435f)

**Comment by olegklimov** [comment]
I know this one, that's a HF-style problem

**Comment by olegklimov** [comment]
Maybe solved by https://github.com/smallcloudai/refact/pull/243
I didn't find a problem with forward_to_hf_endpoint.rs

**Comment by hazratisulton** [comment]
Ok. It works.
